alphagov/govuk-terraform-provisioning

projects/mysql_xtrabackups/resources/storage_and_access.tf
This creates buckets to allow streaming MySQL backups.
Please note a bucket has already been deployed in the test environment.
=> Add S3 buckets for mysql_xtrabackups

projects/wal-e_backups_api-postgresql/resources/storage_and_access.tf, projects/wal-e_backups_postgresql/resources/storage_and_access.tf, projects/wal-e_backups_transition-postgresql/resources/storage_and_access.tf
There are three instances of PostgreSQL in the stack which will need backing up. This makes three distinct WAL-E buckets for each one to use.
=> Make distinct WAL-E S3 buckets

packer/README.md, packer/ami.json, packer/scripts/provision.sh
These machines will be backed by Elastic Block Store (EBS) for use in EC2.
The source AMI is from https://cloud-images.ubuntu.com/locator/ec2/ and has the following properties:
- eu-west-1
- 14.04 LTS Trusty
- amd64
- [HVM (hardware virtual machine) instead of PV (paravirtual)][1]
because more EC2 machine types seem to be available for HVM images
The name of the source AMI in the AWS console is: `ubuntu/images/hvm/ubuntu-trusty-14.04-amd64-server-20160314`
[1]: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html
---
We've added a basic provisioning script which installs our version of Puppet onto the AMI.
We also install build-essential because it's required for lots of things (eg make) and is already present on all of our machines.
We should potentially use our …
=> Add packer config

packer/ami.json
Our AMIs don't contain any secret information so we should make them public for now.
> A list of groups that have access to launch the resulting AMI(s).
> By default no groups have permission to launch the AMI. all will
> make the AMI publicly accessible. AWS currently doesn't accept
> any value other than "all".
=> Make AMIs public

modules/admins/main.tf
This was missed as we use the names in two places.
=> Finish the removal of Matt and the addition of Jon

modules/private_s3_bucket/README.md, modules/private_s3_bucket/main.tf, modules/private_s3_bucket/templates/readwrite_policy.tpl, projects/govuk_attachments/resources/storage_and_access.tf
This is used to back-up whitehall attachments. 
Ticket: https://trello.com/c/DTByYmW1/51-sync-whitehall-attachments-to-s3
Related: https://github.com/alphagov/govuk-puppet/pull/4336
=> Create bucket for whitehall attachments

projects/mysql_xtrabackups/resources/storage_and_access.tf, projects/wal-e_backups_api-postgresql/resources/storage_and_access.tf, projects/wal-e_backups_postgresql/resources/storage_and_access.tf, projects/wal-e_backups_transition-postgresql/resources/storage_and_access.tf, projects/whitehall_mysql_xtrabackups/resources/storage_and_access.tf
Well, not that many. Just ensure that a few are private not public, and add another one for Whitehall MySQL backups.
=> Many bucket changes

projects/transition-logs-backups/resources/storage_and_access.tf
We want the lowest-cost storage class for these logs as they will
seldomly be accessed, such as in a DR scenario. Unfortunately
terraform does not currently support lifecycle configuration, so
we will need to manage this aspect manually.
=> sets up S3 bucket for transition logs

modules/paired_user/templates/readonly_policy.tpl
Not allowing this makes the public nature a little pointless as you
require an exact object name for anything to work.
=> Allow listing of the public buckets

projects/wal-e_backups_transition-postgresql/resources/production/env_sync_user.tf
This adds a read-only user to be used for environment syncs. It needs to be in Production only as this is the only environment that we wish to sync from.
I've tried to keep this in line with how we do things but I don't think I've got it quite right so will probably need some guidance.
=> Add env-sync RO user

modules/private_s3_bucket/main.tf, projects/govuk_attachments/resources/storage_and_access.tf
This adds an option for versioning an S3 bucket in a module, and adds an example use case within a project.
Note: not sure if this actually should be written as a string or a boolean, will test. 
As per the docs here https://www.terraform.io/docs/providers/aws/r/s3_bucket.html
=> Add option for versioning

projects/govuk_attachments/resources/production/env_sync_user.tf
This adds a read-only user in Production only for use with environment syncing. The user needs to be able to use s3cmd sync to seed the files and then download into the Staging and/or Integration environment.
=> Add env sync user for attachments

projects/lambda_app_bucket/resources/s3-buckets.tf
Code will change for the lambda function so we want to ensure we can
roll back to older versions in the S3 bucket.
=> Add versioning to lambda bucket

projects/govuk_attachments/resources/production/env_sync_user.tf
We have environment syncs from the Production bucket to Staging and Integration, so ideally we want two read-only users to the Production for each environment. Previously I had only created one, so this change adds a policy attachment to create these users without repeating any code.
=> Add separate RO users

projects/mysql_xtrabackups/resources/production/env_sync_user.tf
This adds the read-only users to Production to allow environment syncing to Staging and Integration.
=> Add MySQL backup env sync users

projects/email_alert_notifications/resources/email_alert_notifications.tf
This key is specific to the fact this is an email alert notification Lambda function.
We could pass this bit in as part of LAMBDA_FILENAME but I'm not sure it will ever change.
=> Fix s3_key for Lambda function source

projects/email_alert_notifications/resources/email_alert_notifications.tf
This resource type is vaguely named when it should be more specific.
=> Make resource type more defined

modules/private_s3_bucket/templates/readwrite_policy.tpl
We have some functions which moves stuff around in buckets using the
private_s3_bucket module. It seems that without some permissions the
user is unable to do stuff like move objects around and (more obviously)
delete objects for the move. I tested manually and it seems the ACL
permissions are required.
/cc @deanwilson
=> Update permissions of RW user

projects/mongodb-backup-s3/resources/storage_and_access.tf
Some slight refactoring so that we're using the private module policy for our mongo backups in S3. Added a bucket for mongo daily backups.
=> Add Mongodb daily backup S3 bucket

projects/mongodb-backup-s3/resources/storage_and_access.tf, projects/mongodb-backup-s3/resources/templates/readwrite_policy.tpl
For Mongo backups to S3 we have short term daily backups and a different bucket for daily longer term backups.
This adds the code to create two buckets that are owned by a single user.
=> One user two buckets for Mongo S3 backups

modules/private_s3_bucket/main.tf, projects/mongodb-backup-s3/resources/storage_and_access.tf, projects/mysql_xtrabackups/resources/storage_and_access.tf, projects/wal-e_backups_api-postgresql/resources/storage_and_access.tf, projects/wal-e_backups_postgresql/resources/storage_and_access.tf, projects/wal-e_backups_transition-postgresql/resources/storage_and_access.tf
We should enable and deploy lifecycles in S3 buckets that we use for backups so that we don't keep backups forever and waste lots of money. 
This adds the feature. Further details in commits. 
/cc @rjw1 for lifecycle lengths in https://github.com/alphagov/govuk-terraform-provisioning/commit/ac105ab0a5ae38fbf69167e072f8970a4a61c3e8
=> Enable lifecycles in buckets

modules/private_s3_bucket/README.md, modules/private_s3_bucket/main.tf, projects/mongodb-backup-s3/resources/storage_and_access.tf
While verifying backups we noticed that the lifecycle policy was not removing what we thought were expired files.
We had used the argument noncurrent to specify the files we wanted to apply the lifecycle policy to.
This is incorrect because each backup has a unique name due to the timestamp, therefore making each file current.
Removing the noncurrent prefix will enable the lifecycle policy to target the right files.
Applies to bucket "govuk-mongodb-backup-s3"
Set expiration to 7 days on objects within this bucket.  After 7 days the object changes state from 'current_version' to 'previous_version'.
Once object is in 'previous_version' state.  We apply 'noncurrent' version policy which will permanently delete object after 7 days.
Applies to bucket "govuk-mongodb-backup-s3-daily"
Modified …
=> MongoDB bucket Lifecycles

projects/whitehall_mysql_xtrabackups/resources/storage_and_access.tf
If or when we backup Whitehall MySQL data to S3 we'd probably want some lifecycle
rules enabled.
=> Add lifecycle rule to Whitehall backups

projects/elasticsearch_s3_snapshots/README.md, projects/elasticsearch_s3_snapshots/resources/storage_and_access.tf, projects/elasticsearch_s3_snapshots/resources/templates/readwrite_policy.tpl
What
Part of the disaster recovery work. Relates to https://github.com/alphagov/govuk-puppet/pull/4637
The s3 resources needed for backing up snapshots have not yet been provisioned.
How
Create an S3 elasticsearch project to provision buckets, accounts and lifecyle rules for both elasticsearch clusters.
- Snapshots will expire after 6 months and be deleted 1 month after that
=> Elasticsearch Snapshot Buckets

projects/elasticsearch_s3_snapshots/resources/storage_and_access.tf, projects/elasticsearch_s3_snapshots/resources/templates/readwrite_policy.tpl
Renaming resources to reflect changes made in this PR: https://github.com/alphagov/govuk-puppet/pull/4917
Bucket name format is govuk-<cluster class>-<environment>
i.e. govuk-logs-elastcsearch-integration
The logic and policies remain the same.
=> Elasticsearch Snapshot Buckets 2

projects/elasticsearch_s3_snapshots/resources/templates/readwrite_policy.tpl
Correcting a spelling mistake which prevented the correct policy from being applied.
Relates to https://github.com/alphagov/govuk-terraform-provisioning/pull/75
=> Elasticsearch S3 Buckets 3

projects/developer_docs/resources/automated-user-iam.tf, projects/developer_docs/resources/buckets.tf, projects/developer_docs/resources/templates/read_write_user.tpl, projects/developer_docs/resources/variables.tf
This commit adds terraform instructions to create a bucket for the developer documentation on GOV.UK. It will be served from docs.publishing.service.gov.uk (either via a reverse proxy or via cloudfront, we aren't sure what's possible yet).
The bucket has one user, which can read & write. It will probably be used to set up automatic deployment from jenkins.
The bucket is exposed as a website, which means that after uploading the files it should be publicly accessible from:
https://govuk-developer-documentation-integration.s3.amazonaws.com/
https://govuk-developer-documentation-staging.s3.amazonaws.com/
https://govuk-developer-documentation-production.s3.amazonaws.com/
http://govuk-developer-documentation-integration.s3-website-eu-west-1.amazonaws.com/ …
=> Add bucket to host developer documentation

projects/user_management/resources/integration/custom_formats.tf, projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/custom_formats.tf, projects/user_management/resources/production/users.tf
We require access to S3 to upload the latest Mapit database dumps, at least every three months. Currently only Brendan Butler and Simon Hughesdon from the Custom team are users, which is a bottle neck for us when doing this work. Adding two more Custom team members should alleviate this.
=> Add davidbasalla and deborahchua

projects/datastore-offsite-backups/resources/production/buckets_and_access.tf, projects/datastore-offsite-backups/resources/templates/read_write_user.tpl, projects/datastore-offsite-backups/resources/variables.tf
An s3 bucket which serves as the endpoint for datastore backups.
The lifecycle rules have not been officially defined but as they are?  
* Versioning is enabled 
* Versions stay current for one day (because backups are taken daily) 
* After 30 days of being non_current versions.  Backups are transitioned to the **_STANDARD_IA_** storage class (_saves Money_).
* **No data is deleted**
User, govuk-offsite-backup's keys will be generated by hand from the console.
See https://trello.com/c/y3JIRupU
=> GOVUK offsite backckups

modules/admins/main.tf, projects/user_management/resources/groups.tf, projects/user_management/resources/integration/infrastructure_team.tf, projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/infrastructure_team.tf, projects/user_management/resources/production/users.tf, projects/user_management/resources/staging/infrastructure_team.tf, projects/user_management/resources/staging/users.tf
Replace the old `modules/admin/main.tf` method of adding users (which doesn't work) with a new style team in `user_management`.
=> Add infrastructure team

tools/create-console-password.sh, tools/generate-access-keys.sh
Just to save 5 seconds when deploying a new user to create keys, and it doesn't hurt to have this saved somewhere.
=> Create tools directory

projects/datastore-offsite-backups/resources/templates/read_write_user.tpl
The initial backup worked, but in trying to run future backups duplicity threw a 403 when trying to connect to the S3 bucket. I believe it may have been trying to move or do something with the files in the bucket.
It's easiest to just allow full permission by that user. It only has access to that bucket.
Note: I have devops'ed this change to get backups working, but this will need to be deployed to ensure the terraform state file doesn't get out of sync.
=> Adjust govuk-backup S3 permissions

projects/s3-mirrors/README.md, projects/s3-mirrors/resources/buckets.tf, projects/s3-mirrors/resources/mirror-access-policy.tf
This adds necessary terraform to construct both a S3 bucket and
the appropriate user to write to it for mirroring.
=> Add S3 bucket for mirroring

projects/dns-tfstate-store/README.md, projects/dns-tfstate-store/resources/buckets.tf
We need to store the DNS terraform state in a remote location. This
adds an S3 bucket that can be used for this.
=> Add a bucket for storing DNS tfstate files

Rakefile, projects/s3-mirrors/resources/mirror-access-policy.tf
This fixes several errors found whilst deploying terraform to
integration that were not picked up by e.g. `terraform plan`.
This will now create an S3 bucket, user and appropriate policy in AWS
for use creating site mirrors.
=> Fix bugs in initial terraform resources

projects/s3-mirrors/resources/buckets.tf, projects/s3-mirrors/resources/mirror-crawler-write-policy.tf, projects/s3-mirrors/resources/mirror-fastly-read-policy.tf
We want to use S3 as a failover mirror. This means fastly needs to be
able to access the contents of the mirror bucket. This adds an IP
based access policy to the bucket that allows fastly to read it.
=> Add policy to allow Fastly access to the S3 mirror bucket

projects/s3-mirrors/resources/mirror-crawler-write-policy.tf, projects/s3-mirrors/resources/mirror-fastly-read-policy.tf
The crawler writer did not have full write access to the govuk mirror buckets. This corrects that problem by granting it full permissions on both the bucket and the contents of the bucket.
This also fixes a bug found in the process of testing this where the fastly read policy was missing a principal.
=> Fix s3 mirror policy

projects/datastore-offsite-backups/resources/buckets_and_access.tf
Duplicity has lots of strange errors related to orphaned files and seems to run a full backup each time it runs, and doesn't leave any old backups.
I think this may be related to the lifecycle rule of a single day. Duplicity itself should deal with the clean up, and I feel that having both versioning and lifecycles enabled on the bucket complicate matters unnecessarily.
Deployment will require emptying the bucket, destroying it and redeploying it.
=> Remove lifecycle and versioning

projects/s3-mirrors/resources/buckets.tf
Enable the logging option on the S3 mirror bucket, and create a
different bucket to store the access logs.
=> Enable logging on S3 mirror buckets

projects/user_management/resources/groups.tf, projects/user_management/resources/integration/ci.tf, projects/user_management/resources/integration/users.tf
As part of our new Training environment, we want Jenkins to be able
to launch EC2 instances automatically on the Integration account. This
change adds a policy, group and user that we can use from Jenkins
to do this job
Link to EC2 policy example: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policies-ec2-console.html#ex-launch-wizard
=> Add user, group and policy for govuk-ci user on Integration

projects/user_management/resources/integration/infrastructure_team.tf
`resource 'aws_iam_group_membership.infrastructure_team' config: unknown resource 'aws_iam_user.anafernandez' referenced in variable aws_iam_user.anafernandez.name`
Will return to this at a later time.
=> Remove Ana as it caused an error

Rakefile, projects/s3-mirrors/resources/buckets.tf, projects/s3-mirrors/resources/mirror-pingdom-read-policy.tf, projects/s3-mirrors/resources/pingdom_probe_ips.sh
We want to add Pingdom checks for our S3 mirrors so we need to whitelist
the probe IPs. These IPs are likely to change, but they can be pulled
automatically as explained in
https://help.pingdom.com/hc/en-us/articles/203682601-Pingdom-probe-servers-IP-addresses
To manage these IPs automatically, there is a bash script that populates
a Terraform external data source. It's been kept very simple so we don't
have to install dependencies just for this on the servers. There is a limitation
in Terraform that it can only pull string values from external data sources
https://github.com/hashicorp/terraform/issues/12256
so we need to manipulate the string in the Terraform code.
=> Add S3 mirror policy for Pingdom IPs

projects/training-environment/resources/instance_profile_role.tf, projects/training-environment/resources/network.tf
Terraform resources to create a basic network stack and policies
for our network environment. The training VM consumes the remote
state file of this stack to locate its subnet, instance profile
and security groups.
We should update this stack later to move everything to a private
subnet and use ELBs, EIPs, etc.
=> Add network and security stack for GOVUK Training environment

Rakefile, projects/analytics_logging/resources/bucket_and_access.tf
This will receive logs of the assets service for just `/static/a?`.
This will later be extended with additional roles for analysis of the
collected logs.
Also includes a fix for `rake plan`
=> Configure an S3 bucket for Fastly to deposit logs in

projects/s3-mirrors/resources/pingdom_probe_ips.sh
The whitespace is preventing the rest of IPs in the policy from being
evaluated.
=> Fix whitespace in Pingdom IP list

Rakefile
This ensures we print the value of `maximum_terraform_version` instead
of 'maximum_terraform_version'.
=> Fix string interpolation in README

projects/asset-manager/resources/buckets.tf, projects/asset-manager/resources/users.tf, projects/asset-manager/resources/variables.tf
We're updating the Asset Manager app to store and serve files from AWS
S3. This commit adds an asset-manager project to configure the S3 bucket
for file storage and the IAM user that can read/write files in that
bucket.
=> Add asset-manager project

README.md, Rakefile
These changes allow you to run the standard Rake tasks to plan/apply changes even if you don't have access to the GOV.UK S3 buckets which store Terraform state for the various environments by using your own S3 buckets.
This isn't necessarily the best way to solve this problem, because the Terraform state S3 bucket name is hard-coded elsewhere in the repo. However, given that we understand that this repo is likely to disappear in the near future, it feels like a pragmatic solution to the problem we were having.
=> Make Terraform state S3 bucket configurable

projects/asset-manager/resources/buckets.tf, projects/asset-manager/resources/integration/bucket-policy.tf
We want to experiment with having Asset Manager redirect asset URLs to objects on S3 - see [this pull request][1] for details. Note that this experimental Asset Manager behaviour is disabled by default, but can be enabled [using environment variables or on a per-request basis using a query string parameter][2].
Previously the default bucket policy did not allow public read access, but now that we want to redirect requests and have S3 serve the asset to the end-user, we need to add an explicit policy to the bucket to allow public read access.
We considered setting the policy on individual objects, but decided it would be simpler to apply it to the bucket as a whole and then create a separate bucket if we need some objects to have a more restrictive
policy.
Note that we will want to create …
=> Add "public read" policy to Asset Manager S3 bucket

projects/asset-manager/resources/users.tf
It seems that we shouldn't be creating IAM access keys using Terraform
for the following reasons:
1. This results in the IAM user's access and secret keys being stored in
the .tfstate file
2. The infrastructure team have a separate process for creating/managing
IAM access keys
In order to test this change I manually added a second access key to the
asset manager user in my AWS account. This replicates the access key
that has been manually added by the infrastructure team in production.
I applied the change and observed:
* The original access key was removed from the IAM user
* The manually created access key remained on the IAM user
* The access and secret keys were removed from the .tfstate file
=> Remove IAM Access Key for Asset Manager user

projects/asset-manager/resources/users.tf
Adding this permission means that we receive a 404 (Not Found) response
instead of a 403 (Permission Denied) response if the IAM user requests
an object that doesn't exist.
We're currently changing asset-manager so that it can serve asset
requests by proxying to S3. We want the external HTTP behaviour to
remain constant irrespective of whether the asset is served from the
file system or from S3. This change means that requesting an asset that
doesn't exist on S3 will now respond with a 404, which is the same
response we'd see if we were to request an asset that didn't exist on
the filesystem.
I've tested this change in our GFR AWS account and can confirm that it
works as expected.
=> Add S3:ListBucket permission to asset-manager IAM user

projects/analytics_lambdas/main.tf, projects/analytics_lambdas/variables.tf
Part of https://trello.com/c/nbpTiCbi/1102-publish-aws-lambda-to-process-public-api-logs
Terraform AWS configuration for lambda function to track public API request logs on S3.
The bucket config is already done [here](https://github.com/alphagov/govuk-terraform-provisioning/blob/master/projects/analytics_logging/resources/bucket_and_access.tf).
This config should give the lambda read access to the named S3 bucket and allow the lambda to execute from the bucket.
See https://github.com/alphagov/govuk-lambda-app-deployment/pull/10 and https://github.com/alphagov/govuk-lambda-app-deployment/pull/11 for lambda code + deployment.
=> Configure AWS lambda for public API tracking

projects/asset-manager/resources/policies.tf, projects/asset-manager/resources/production/buckets.tf, projects/asset-manager/resources/production/buckets_for_backups.tf, projects/asset-manager/resources/production/policies_for_backups.tf, projects/asset-manager/resources/production/providers_for_backups.tf, projects/asset-manager/resources/production/roles_for_backups.tf, projects/asset-manager/resources/users.tf, projects/asset-manager/resources/variables.tf
This creates a new backup S3 bucket in a different region in preparation for enabling cross-region replication on the main S3 bucket currently used by the Asset Manager app.
The motivation behind this is to (eventually) replace the nightly cron job which uses Duplicity to backup the Asset Manager files from NFS to one of the off-site backup S3 buckets. This will be a step towards being able to decommission NFS, or at least the Asset Manager bit of it.
Note that this PR does *not* include actually enabling replication, because there was an ordering problem with switching on versioning on the main bucket and enabling replication. I've opened [a 2nd PR][2] to actually enable replication making use of all the resources created and modified by the changes in this PR. I plan to explain how I …
=> Prepare to enable cross-region replication on production Asset Manager S3 bucket

modules/private_s3_bucket/main.tf, projects/rummager-elasticsearch-snapshots/README.md, projects/rummager-elasticsearch-snapshots/resources/main.tf
This uses the module we used to use extensively to create a private S3 bucket and user. I can see no reason not to use this module, and have added a variable so we can set the lifecycle expiration in days.
After some discussion, we decided we should only keep 7 days worth of snapshots as it's extremely unlikely we would require anything historical.
=> Create bucket for rummager-elasticsearch-snapshots

projects/asset-manager/resources/buckets.tf, projects/asset-manager/resources/policies_for_env_sync_bucket.tf, projects/asset-manager/resources/production/policies_for_env_sync_user.tf, projects/asset-manager/resources/production/users_for_env_sync.tf, projects/asset-manager/resources/variables.tf
The idea is that a new job in the `env-sync-and-backup` repo will SSH onto a production machine and use the `aws s3 sync` command line tool to perform a nightly sync of the production assets S3 bucket to the staging & integration assets S3 buckets.
* Adds a new IAM user to the Asset Manager project in the production environment with minimal read access to the production assets S3 bucket and minimal write access to the staging & integration assets S3 buckets.
* Adds a bucket policy to the staging & integration assets S3 buckets to allow minimal write access to the new production IAM user mentioned above.
* Note that, because each Terraform environment has its own separate AWS account, we need to pass in the AWS account ID as a Terraform variable, `production_aws_account_id`, in order to be …
=> Allow syncing of assets between environments

projects/user_management/resources/groups.tf, projects/user_management/resources/integration/2ndline.tf, projects/user_management/resources/integration/users.tf
- Infrastructure are finding people want to manage S3 buckets and don't
have access. It would be easier if there were a shared 2ndline
account.
=> Add an AWS user for 2ndline with access to all S3 buckets

old-projects/base_aws_infrastructure/resources/office-ips.tf
We're not in that building and even though this code is no longer used
it's better not to have it floating around.
=> Remove aviation house ips.

projects/user_management/resources/groups.tf
- When trying to deploy asset-manager changes, it failed on not having
access to `GetUser` and `GetPolicy`. I don't know if it'll need more
permissions, but we can add them if it does.
=> Give the 2ndline user more permissions

projects/user_management/resources/groups.tf, projects/user_management/resources/integration/ci.tf, projects/user_management/resources/integration/users.tf
Revert ee111d74b1a3e425393a1d92e12539b1400e86d5
The govuk-ci user, group and policy were configured to automate
the training environment refresh from Jenkins. The training
environment doesn't exist any more, so this needs to go.
=> Remove govuk-ci (training environment) from user-management

projects/asset-manager/resources/policies.tf
This allows new Rake tasks which make it easier to delete assets off S3.
[Trello Card](https://trello.com/c/bod2J0d5/393-make-the-process-of-deleting-assets-off-s3-easier)
=> Allow asset-manager to delete objects
