alphagov/govuk-terraform-provisioning

modules/admins/main.tf
Terraform now matches my perceived gender
=> Update my name

projects/mongodb-backup-s3/resources/storage_and_access.tf
See mongodb/manifests/s3backup directory in puppet for more
info.
=> adds S3 bucket for mongodb-backup-s3 script

modules/admins/main.tf
=> Staff changes

Rakefile
Add a wrapper to destroy terraform provisioned resources. I've needed this quite a lot lately.
=> Add a wrapper for destroy

projects/base_aws_infrastructure/resources/iam-password-policy.tf
This choice of criteria is from a discussion with @alexmuller
=> Add a basic password policy

projects/wal-e_backups_api-postgresql/resources/storage_and_access.tf, projects/wal-e_backups_postgresql/resources/storage_and_access.tf, projects/wal-e_backups_transition-postgresql/resources/storage_and_access.tf
This is in line with the S3 naming convention: https://docs.aws.amazon.com/AmazonS3/latest/UG/CreatingaBucket.html
=> Convert underscores to hyphens

projects/lambda_app_bucket/resources/s3-buckets.tf
We've not enabled versioning or any extra permissions yet as we
have a further ticket to discuss and decide on that approach.
=> Create a bucket to store lambda zip files for later deployment

modules/admins/main.tf
=> Remove Jon Auman

Rakefile
If the `system()` call errors Ruby will just happily continue unless we explicitly check for the exit code.
=> Always check the exit code of system calls

projects/base_aws_infrastructure/resources/staging/environment-ips.tf
The IP has changed, but this will be tricky to deploy without some
manual intervention. :(
This is the Staging IP: 
```
lauramartin@staging-jenkins-1:~$ curl icanhazip.com
195.225.216.150
```
=> Staging has moved to London

modules/admins/main.tf
Giving myself access to aws resources by creating an account
=> AWS account for mikael

Rakefile
Our stuff doesn't support the newer terraform 0.7 stuff.
=> Add maximum_terraform_version

projects/user_management/resources/production/custom_formats.tf
This bucket should be in produciton and they'll need access to it.
=> Add users to production

projects/user_management/resources/production/users.tf
=> Deploy the users to this environment too.

projects/user_management/resources/integration/infrastructure_team.tf, projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/infrastructure_team.tf, projects/user_management/resources/production/users.tf, projects/user_management/resources/staging/infrastructure_team.tf, projects/user_management/resources/staging/users.tf
Manage anafernandez account with Terraform and enable access to Production
=> Manage anafernandez account with Terraform and enable access to Prod

projects/user_management/resources/integration/infrastructure_team.tf, projects/user_management/resources/integration/users.tf
My account was created manually on Integration, so this code
would probably update the user. Do not manage the  account with
Terraform for now, I'll sort it out when I have more time
=> Do not manage existing anafernandez account on Integration

projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/infrastructure_team.tf, projects/user_management/resources/production/users.tf, projects/user_management/resources/staging/infrastructure_team.tf, projects/user_management/resources/staging/users.tf
Add to infrastructure team, giving full access.
=> Add account for paulbowsher

projects/user_management/resources/groups.tf
Update CI original policy to include missing permissions.
=> Update CI policy

modules/admins/main.tf, projects/user_management/resources/integration/infrastructure_team.tf, projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/infrastructure_team.tf, projects/user_management/resources/production/users.tf, projects/user_management/resources/staging/infrastructure_team.tf, projects/user_management/resources/staging/users.tf
Added myself to the admin user list.
=> Add user "stephenharker" to admins.

old-projects/base_aws_infrastructure/resources/office-ips.tf, projects/training-environment/resources/network.tf
[Trello card](https://trello.com/c/G8tsen8Y/296-add-whitechapel-ip-address-ranges-to-our-config)
=> Add White Chapel Building IP Addresses

modules/admins/main.tf
Trello card:
https://trello.com/c/1QxAqimW/297-leaver-alex-muller-16-june
=> Remove Alex Muller

projects/user_management/resources/production/infrastructure_team.tf, projects/user_management/resources/production/users.tf, projects/user_management/resources/staging/infrastructure_team.tf, projects/user_management/resources/staging/users.tf
Adding Issy to Production would enable her to manage DNS records ;)
=> Add Issy everywhere

projects/user_management/resources/integration/custom_formats.tf, projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/custom_formats.tf, projects/user_management/resources/production/users.tf
David needs access to the Mapit bucket as he's on Benchmarking who are responsible for updating postcode and boundary line data regularly.
=> Add David Silva

projects/asset-manager/resources/policies.tf, projects/asset-manager/resources/production/buckets.tf, projects/asset-manager/resources/production/buckets_for_backups.tf, projects/asset-manager/resources/production/policies_for_backups.tf, projects/asset-manager/resources/production/providers_for_backups.tf, projects/asset-manager/resources/production/roles_for_backups.tf, projects/asset-manager/resources/users.tf, projects/asset-manager/resources/variables.tf
The changes in this PR enable cross-region replication on the main S3 bucket currently used by the Asset Manager app.
The motivation behind this is to (eventually) replace the nightly cron job which uses Duplicity to backup the Asset Manager files from NFS to one of the off-site backup S3 buckets. This will be a step towards being able to decommission NFS, or at least the Asset Manager bit of it.
Note that he changes in this PR are intended to be applied *after* the changes in [the preparatory PR][2]. The changes in this PR are all in the final commit with subject line: "Enable replication on Asset Manager S3 bucket in production". I plan to rebase this branch against master after the preparatory PR has been merged. I had to split the changes into two PRs, because there was an ordering …
=> Enable cross-region replication on production Asset Manager S3 bucket

projects/user_management/resources/production/2ndline.tf, projects/user_management/resources/production/users.tf, projects/user_management/resources/staging/2ndline.tf, projects/user_management/resources/staging/users.tf
- I only did integration in #144. :-(
=> Add a 2ndline user in AWS staging and production

projects/asset-manager/resources/policies_for_env_sync_bucket.tf, projects/asset-manager/resources/production/policies_for_env_sync_user.tf
The `env-sync-and-backup` project does a nightly sync of assets from the production S3 bucket to the staging and integration buckets. This is achieved using a env sync production user, `govuk-assets-production-env-sync-user` which has permission to get, put & delete objects in the target buckets. Unfortunately this meant the sync-ed objects had their owner set to the env sync production user. This in turn meant that the Asset Manager AWS user in staging & integration had no permission to do anything with the sync-ed objects - not even read them!
The way we've decided to fix this is to change the `aws s3 sync` command used in the `env-sync-and-backup` project to use the `acl` option set to `bucket-owner-full-control` (see https://github.com/alphagov/env-sync-and-backup/pull/37). However, …
=> Add s3:PutObjectAcl permission for production env sync user

old-projects/base_aws_infrastructure/resources/iam-password-policy.tf
This is now implemented in https://github.com/alphagov/govuk-aws/pull/413
in the new, supported, repo.
=> Remove the password policy management.

projects/user_management/resources/integration/infrastructure_team.tf, projects/user_management/resources/integration/users.tf
trello: https://trello.com/c/ZIiWko8x/413-leaver-tim-mower
=> Remove Tim Mower

projects/user_management/resources/integration/custom_formats.tf, projects/user_management/resources/integration/users.tf, projects/user_management/resources/production/custom_formats.tf, projects/user_management/resources/production/users.tf
Brendan has left the GOV.UK programme.
See https://trello.com/c/JH9t4UfX/39-govuk-mover-brendan-butler
=> Remove Brendan Butler

projects/user_management/resources/integration/training_platform.tf, projects/user_management/resources/integration/users.tf
Trello: https://trello.com/c/GK4ie9lQ/155-leaver-graham-pengelly
=> Remove Graham Pengelly
